import { jsPDF } from 'jspdf';
import { Transaction } from '../types';
import { formatCurrency, formatDate } from './helpers';

export const generateTransactionReceipt = (transaction: Transaction) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // Set font
  doc.setFont('helvetica');

  // Add logo/header
  doc.setFontSize(24);
  doc.setTextColor(0, 128, 128); // Teal color
  doc.text('FinanceTracker', 20, 20);

  // Add receipt title
  doc.setFontSize(18);
  doc.setTextColor(0, 0, 0);
  doc.text('Transaction Receipt', 20, 35);

  // Add receipt details
  doc.setFontSize(12);
  doc.setTextColor(80, 80, 80);

  const details = [
    ['Date:', formatDate(transaction.date)],
    ['Transaction Type:', transaction.type.charAt(0).toUpperCase() + transaction.type.slice(1)],
    ['Category:', transaction.category],
    ['Description:', transaction.description],
    ['Amount:', formatCurrency(transaction.amount)],
    ['Transaction ID:', transaction.id],
  ];

  let yPos = 50;
  details.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, 20, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 70, yPos);
    yPos += 10;
  });

  // Add footer
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  const footer = 'Generated by FinanceTracker on ' + new Date().toLocaleString();
  doc.text(footer, 20, 280);

  // Save the PDF
  doc.save(`transaction-${transaction.id}.pdf`);
};